### ISSUE TITLE
Do not stop build if commit message contains skip message

### ISSUE THREAD

**Issue by dxops** [grosser/travis_dedup#13]
https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

**Comment by grosser** [comment]
I don't see how that would be an issue since the logic is to 'de-duplicate' builds ... if a skip commit comes in and it does not trigger a build then there would be no duplicate build ... so nothing would be cancelled ?

**Comment by dxops** [comment]
@grosser works like you described, thanks!
