### ISSUE TITLE
[feature] Add option --retry

### ISSUE THREAD

**Issue by jmgarnier** [grosser/travis_dedup#9]
When travis is quite busy (when the 🇺🇸 is working basically), it returns a 500. Sometimes, we have to restart manually the build until it Travis finally replies. Record was 7 times in a row.

Example of stacktrace:
```
$ gem install travis_dedup && travis-dedup org/project xxx --pro --branches
Fetching: multipart-post-2.0.0.gem (100%)

Successfully installed travis_dedup-0.5.0
3 gems installed
/home/travis/.rvm/gems/ruby-2.3.1/gems/travis_dedup-0.5.0/lib/travis_dedup.rb:106:in `request': Communication with travis failed when trying to get repos/nedap/dossier/builds (Faraday::Error)
Response: 500 - {"error":"Travis encountered an error, sorry :("}
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/travis_dedup-0.5.0/lib/travis_dedup.rb:84:in `active_builds'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/travis_dedup-0.5.0/lib/travis_dedup.rb:54:in `dedup_builds'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/travis_dedup-0.5.0/lib/travis_dedup.rb:42:in `dedup_message'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/travis_dedup-0.5.0/lib/travis_dedup.rb:33:in `cli'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/travis_dedup-0.5.0/bin/travis-dedup:9:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/travis-dedup:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/travis-dedup:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

We could fix by adding a `--retry` options and enable it by default, say 3 times. If travis keeps failing, build should go ahead so no manual intervention is needed.

I have opened this issue to discuss that feature. Once the behavior is clear,  I can work on it and test it on my fork if you like.

PS: I have been following you since I worked in Berlin in 2010 with `parallel_tests` and I never took the time to thank you. So 🙇 a big thank you for sharing your work. I am still following your blog 😄

**Comment by grosser** [comment]
thanks, `--retry` sounds good / having a sane default

FYI travis is shipping duplicate build cancellation feature atm, so might want to just sit this out for ~3 months :)
